
------ MAKE SURE ASK IS NOT FOR INCLUSIVE PRICEPLANS, THIS QUERY IS FOR PRICEPLANS ONLY

SELECT 
A.SUBSCRIBER_NO, 
A.BAN,
A.EFFECTIVE_DATE, 
A.EXPIRATION_DATE,
A.SOC
INTO #BASE_PP
FROM STAGE.dbo.STG_SUBSCRIBER_PRICE_PLAN A
	WHERE (A.EXPIRATION_DATE IS NULL OR A.EXPIRATION_DATE > GETDATE())
	AND A.EFFECTIVE_DATE <= GETDATE()
	AND A.PRODUCT_TYPE = 'C'
	AND A.SOC = 'DMRMM2501'

-- OUTPUT







--------------------------------------------------------------------- DAVID'S ASK



SELECT DISTINCT BAN, SUBSCRIBER_NO 
INTO #PP_LIST
FROM #BASE_PP


SELECT DISTINCT BAN,
SUBSCRIBER_NO 
INTO #DEP_SOC 
FROM STAGE.dbo.STG_SERVICE_AGREEMENT A
WHERE SOC = 'OPTSPA004'
AND (EXPIRATION_DATE IS NULL OR EXPIRATION_DATE > GETDATE())
	AND EFFECTIVE_DATE <= GETDATE()
	
	
	SELECT A.*
	FROM #PP_LIST A
	JOIN #DEP_SOC B
	ON A.BAN=B.BAN
	AND A.SUBSCRIBER_NO=B.SUBSCRIBER_NO
