SELECT A.SOC AS 'RINGBACK SOC'
,A.FEATURE_CODE AS 'BILLING FEATURE CODE'
, A.RATE AS 'BILLING RATE'
,B.GL_REV_CD AS 'ROLLS INTO'
,B.FEATURE_CATEGORY 
,C.DISC_PLAN_CD AS 'DISCOUNT CODE'
,C.EFFECTIVE_DATE 
,C.ACNT_WEIGHT AS 'DISCOUNT RATE'
,D.SRC_SOC AS 'ELIGIBLE FOR'
INTO #DISCOUNT1
 FROM [STAGE].[dbo].[STG_PP_RC_RATE] A
 JOIN [STAGE].[dbo].[STG_CHARGE_INFO] B
 ON A.FEATURE_CODE=B.FEATURE_CODE
 JOIN [STAGE].[dbo].[STG_DISCOUNT_CATEGORY] C
  ON B.FEATURE_CATEGORY = C.FEATURE_CATEGORY
  JOIN [STAGE].[dbo].[STG_ELIGIBILITY_RELATION] D
  ON C.DISC_PLAN_CD=D.DEST_SOC
 WHERE A.SOC = 'OPTSRA0JJ' --------------------------- BRING IN ALL RINGBACKS  (THEN TAG THE PAID ONES)
   --AND C.EFFECTIVE_DATE = '2011-11-08' --------------------------- DONT FILTER DATES
  AND A.EXPIRATION_DATE IS NULL
  AND D.DEST_SERVICE_TYPE = 'D'