

CREATE TABLE #number
("Number" NUMERIC(20)
,Variable NUMERIC(20)
)

DECLARE @NUMBER AS NUMERIC(20)
SET @NUMBER = 1

WHILE @NUMBER <= 1000         
BEGIN

INSERT INTO #number
("Number")
  SELECT @NUMBER
 
SET @NUMBER = @NUMBER+1
END
GO
   
SELECT DISTINCT NUMBER, (NUMBER/13) AS DIVIDE_13, (NUMBER/31) AS DIVIDE_31
INTO #NUMBER2
FROM #NUMBER

SELECT DISTINCT *
INTO #RESULT
FROM #NUMBER2
WHERE (DIVIDE_13 LIKE '%.000000'
OR DIVIDE_31 LIKE '%.000000')

SELECT SUM(NUMBER) AS RESULT
FROM #RESULT



SELECT *
FROM #RESULT