
DECLARE @INDEX AS NUMERIC(4,0)
DECLARE @MONTH AS NUMERIC(2,0)
DECLARE @YEAR AS NUMERIC(4,0)

set @INDEX = (select MAX (INDEX_NO)       ------------------- TAKE AWAY (-#) FOR LAST WEEK
from [STAGE].[dbo].[STG_TIME_DIM_MONTHLY]
where [EOM] +.9999999 <= GETDATE())

while @INDEX >= 41                  ------------------- (START WEEK)
begin

SET @MONTH = (SELECT DISTINCT [MONTH_DATE] 
FROM [STAGE].[dbo].[STG_TIME_DIM_MONTHLY]
WHERE INDEX_NO = @INDEX)

SET @YEAR = (SELECT DISTINCT [YEAR_DATE]
FROM [STAGE].[dbo].[STG_TIME_DIM_MONTHLY]
WHERE INDEX_NO = @INDEX) 


SELECT @INDEX

SET @INDEX = @INDEX - 1
END
GO