
DECLARE @WEEK AS NUMERIC(4,0)
DECLARE @START AS DATETIME
DECLARE @END AS DATETIME

set @week = (select MAX ([WEEK])        ------------------- TAKE AWAY (-#) FOR LAST WEEK
from [STAGE].[dbo].[STG_TIME_DIM_WEEKLY]
where [ENDDATE] +.9999999 <= GETDATE())

SET @START = (SELECT DISTINCT [STARTDATE] 
FROM [STAGE].[dbo].[STG_TIME_DIM_WEEKLY]
WHERE [WEEK] = @week)

SET @END = (SELECT DISTINCT [ENDDATE]
FROM [STAGE].[dbo].[STG_TIME_DIM_WEEKLY]
WHERE [WEEK] = @week) 

--SELECT @WEEK
--SELECT @START
--SELECT @END
