

-------------------------------------------- VALUEPACK BASE + WEEK over WEEK %CHANGE


---- STEP #1: VARIABALIZE MORE RECENT WEEK 

DROP TABLE #BASE_1
DROP TABLE #BASE_2

DECLARE @CURRENT AS NUMERIC(18,0)
SET @CURRENT = (SELECT MAX(WEEK_NO) FROM [ENTERTAINMENT].[dbo].[RM_VALUEPACKS_WEEKLY])
    
---- STEP #2: TEMP BASE FOR CURRENT WEEK

SELECT WEEK_NO, END_DATE, FRANCHISE = CASE
WHEN FRANCHISE = 'R' THEN 'ROGERS'
ELSE 'FIDO'
END, SUM([CLOSE]) AS "CURRENT BASE"
INTO #BASE_1
FROM [ENTERTAINMENT].[dbo].[RM_VALUEPACKS_WEEKLY]
WHERE WEEK_NO = @CURRENT
AND SOC_TYPE = 'VALUEPACK'
GROUP BY WEEK_NO, END_DATE, FRANCHISE


----- TEMP PREVIOUS WEEK'S BASE
SELECT WEEK_NO, END_DATE, FRANCHISE = CASE
WHEN FRANCHISE = 'R' THEN 'ROGERS'
ELSE 'FIDO'
END, SUM([CLOSE]) AS "PREVIOUS WEEK'S BASE"
INTO #BASE_2
FROM [ENTERTAINMENT].[dbo].[RM_VALUEPACKS_WEEKLY]
WHERE WEEK_NO = @CURRENT-1
AND SOC_TYPE = 'VALUEPACK'
GROUP BY WEEK_NO, END_DATE, FRANCHISE
 
----- SHOW BOTH CURRENT AND PREVIOUS BASE + WEEK OVER WEEK CHANGE IN %   (new - old) / old
    
 SELECT A.END_DATE, A.FRANCHISE, A.[CURRENT BASE], B."PREVIOUS WEEK'S BASE", (([CURRENT BASE] - [PREVIOUS WEEK'S BASE])/[PREVIOUS WEEK'S BASE]) AS "WoW CHANGE"
 FROM #BASE_1 A
 INNER JOIN #BASE_2 B
 ON A.FRANCHISE=B.FRANCHISE
 ORDER BY END_DATE, FRANCHISE DESC